language: python
notifications:
  email:
    on_failure: change

python:
  - "2.7"
env:
  # Default values for common packages, override as needed
  global:
    - CYTHON=0.20
    - PATSY=0.2
    - PANDAS=0.12
    - OPTIONAL=
    - COVERAGE=false
    - PYTHON=2.7

before_install:
  # adapted from statsmodels travis file https://github.com/statsmodels/statsmodels/blob/master/.travis.yml
  # setup anaconda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda
  # Fix for headless TravisCI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # Build package list to avoid empty package=versions; only needed for versioned pacakges
  - PKGS="python=${PYTHON}"
  - PKGS="${PKGS} numpy"; if [ ${NUMPY} ]; then PKGS="${PKGS}=${NUMPY}"; fi
  - PKGS="${PKGS} scipy"; if [ ${SCIPY} ]; then PKGS="${PKGS}=${SCIPY}"; fi
  - PKGS="${PKGS} patsy"; if [ ${PATSY} ]; then PKGS="${PKGS}=${PATSY}"; fi
  - PKGS="${PKGS} pandas"; if [ ${PANDAS} ]; then PKGS="${PKGS}=${PANDAS}"; fi
  - PKGS="${PKGS} Cython"; if [ ${CYTHON} ]; then PKGS="${PKGS}=${CYTHON}"; fi
  - PKGS="${PKGS} pip";

install:
  - conda create --yes --quiet -n pychron-test ${PKGS} ${OPTIONAL}
  - source activate pychron-test
  - conda install --yes --file requirements_tests.txt
  - pip install -r pip_requirements.txt

script: python setup.py test